"""add structured product models

Revision ID: 909aa752bb02
Revises: 3456cd9dd805
Create Date: 2026-01-28 14:59:53.070446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import app

# revision identifiers, used by Alembic.
revision: str = '909aa752bb02'
down_revision: Union[str, Sequence[str], None] = '3456cd9dd805'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('structured_product_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('product_type', sa.String(length=100), nullable=False),
    sa.Column('underlying_symbol', sa.String(length=50), nullable=False),
    sa.Column('payoff_formula', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('maturity_days', sa.Integer(), nullable=False),
    sa.Column('principal', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('fees', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('structured_product_instances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('issuer_user_id', sa.Integer(), nullable=False),
    sa.Column('total_notional', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('maturity_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('replication_trades', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('current_value', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['issuer_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['structured_product_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('investor_user_id', sa.Integer(), nullable=False),
    sa.Column('subscription_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('subscription_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['structured_product_instances.id'], ),
    sa.ForeignKeyConstraint(['investor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_credit_transactions_transaction_type'), table_name='credit_transactions')
    op.add_column('cross_chain_transactions', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_cross_chain_transactions_organization_id'), 'cross_chain_transactions', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'cross_chain_transactions', 'organizations', ['organization_id'], ['id'], ondelete='SET NULL')
    op.alter_column('document_signatures', 'access_token',
               existing_type=sa.VARCHAR(length=255),
               type_=app.db.encrypted_types.EncryptedString(length=255),
               existing_nullable=True)
    op.drop_constraint(op.f('kyc_verifications_user_id_key'), 'kyc_verifications', type_='unique')
    op.create_index(op.f('ix_kyc_verifications_user_id'), 'kyc_verifications', ['user_id'], unique=True)
    op.drop_constraint(op.f('orders_order_id_key'), 'orders', type_='unique')
    op.drop_index(op.f('ix_polymarket_surveillance_alerts_created_at'), table_name='polymarket_surveillance_alerts')
    op.alter_column('securitization_pool_assets', 'asset_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('securitization_pool_assets', 'asset_value',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               nullable=True)
    op.alter_column('securitization_pool_assets', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('sharing_events', 'sender_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('trade_executions_trade_id_key'), 'trade_executions', type_='unique')
    op.alter_column('user_licenses', 'license_number',
               existing_type=sa.VARCHAR(length=255),
               type_=app.db.encrypted_types.EncryptedString(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_licenses', 'license_number',
               existing_type=app.db.encrypted_types.EncryptedString(length=255),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.create_unique_constraint(op.f('trade_executions_trade_id_key'), 'trade_executions', ['trade_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('sharing_events', 'sender_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('securitization_pool_assets', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('securitization_pool_assets', 'asset_value',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               nullable=False)
    op.alter_column('securitization_pool_assets', 'asset_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_index(op.f('ix_polymarket_surveillance_alerts_created_at'), 'polymarket_surveillance_alerts', ['created_at'], unique=False)
    op.create_unique_constraint(op.f('orders_order_id_key'), 'orders', ['order_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_kyc_verifications_user_id'), table_name='kyc_verifications')
    op.create_unique_constraint(op.f('kyc_verifications_user_id_key'), 'kyc_verifications', ['user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('document_signatures', 'access_token',
               existing_type=app.db.encrypted_types.EncryptedString(length=255),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_constraint(None, 'cross_chain_transactions', type_='foreignkey')
    op.drop_index(op.f('ix_cross_chain_transactions_organization_id'), table_name='cross_chain_transactions')
    op.drop_column('cross_chain_transactions', 'organization_id')
    op.create_index(op.f('ix_credit_transactions_transaction_type'), 'credit_transactions', ['transaction_type'], unique=False)
    op.drop_table('product_subscriptions')
    op.drop_table('structured_product_instances')
    op.drop_table('structured_product_templates')
    # ### end Alembic commands ###
