"""Add document_type to generated_documents

Revision ID: 9507b9673be9
Revises: 33ad1d92fa83
Create Date: 2026-01-13 16:26:18.975239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9507b9673be9'
down_revision: Union[str, Sequence[str], None] = '33ad1d92fa83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_schedules_loan_asset_id'), table_name='payment_schedules')
    op.drop_index(op.f('ix_payment_schedules_scheduled_date'), table_name='payment_schedules')
    op.drop_index(op.f('ix_payment_schedules_status'), table_name='payment_schedules')
    op.drop_table('payment_schedules')
    op.alter_column('applications', 'application_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('applications', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'draft'::character varying"))
    op.drop_index(op.f('ix_applications_application_type'), table_name='applications')
    op.drop_index(op.f('ix_clause_cache_template_field_context'), table_name='clause_cache')
    op.alter_column('deals', 'is_demo',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_constraint(op.f('deals_deal_id_key'), 'deals', type_='unique')
    op.alter_column('demo_seeding_status', 'errors',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.add_column('document_signatures', sa.Column('signer_name', sa.String(length=255), nullable=False))
    op.add_column('document_signatures', sa.Column('signer_role', sa.String(length=100), nullable=True))
    op.add_column('document_signatures', sa.Column('signature_method', sa.String(length=50), nullable=False))
    op.add_column('document_signatures', sa.Column('signature_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('document_signatures', sa.Column('signed_at', sa.DateTime(), nullable=False))
    op.add_column('document_signatures', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.alter_column('document_signatures', 'document_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_document_signatures_signature_request_id'), table_name='document_signatures')
    op.drop_index(op.f('ix_document_signatures_signature_status'), table_name='document_signatures')
    op.drop_column('document_signatures', 'signature_provider')
    op.drop_column('document_signatures', 'signature_provider_data')
    op.drop_column('document_signatures', 'signed_document_path')
    op.drop_column('document_signatures', 'expires_at')
    op.drop_column('document_signatures', 'signers')
    op.drop_column('document_signatures', 'signature_request_id')
    op.drop_column('document_signatures', 'signed_document_url')
    op.drop_column('document_signatures', 'signature_status')
    op.drop_column('document_signatures', 'completed_at')
    op.drop_column('document_signatures', 'requested_at')
    op.alter_column('document_versions', 'extraction_method',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'simple'::character varying"))
    op.alter_column('documents', 'sustainability_linked',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('idx_documents_template_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_is_demo'), table_name='documents')
    op.create_index(op.f('ix_documents_template_id'), 'documents', ['template_id'], unique=False)
    op.drop_column('documents', 'is_demo')
    op.add_column('generated_documents', sa.Column('document_type', sa.String(length=100), nullable=True))
    op.add_column('generated_documents', sa.Column('source_type', sa.String(length=100), nullable=True))
    op.drop_index(op.f('idx_generated_documents_created_by'), table_name='generated_documents')
    op.drop_index(op.f('idx_generated_documents_source_document_id'), table_name='generated_documents')
    op.drop_index(op.f('idx_generated_documents_status'), table_name='generated_documents')
    op.drop_index(op.f('idx_generated_documents_template_id'), table_name='generated_documents')
    op.create_index(op.f('ix_generated_documents_created_by'), 'generated_documents', ['created_by'], unique=False)
    op.create_index(op.f('ix_generated_documents_source_document_id'), 'generated_documents', ['source_document_id'], unique=False)
    op.create_index(op.f('ix_generated_documents_status'), 'generated_documents', ['status'], unique=False)
    op.create_index(op.f('ix_generated_documents_template_id'), 'generated_documents', ['template_id'], unique=False)
    op.create_index(op.f('ix_inquiries_assigned_to'), 'inquiries', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_inquiries_resolved_by'), 'inquiries', ['resolved_by'], unique=False)
    op.alter_column('lma_templates', 'template_code',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('lma_templates', 'version',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('lma_templates', 'file_path',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.drop_index(op.f('idx_lma_templates_category'), table_name='lma_templates')
    op.drop_index(op.f('idx_lma_templates_subcategory'), table_name='lma_templates')
    op.drop_index(op.f('idx_lma_templates_template_code'), table_name='lma_templates')
    op.drop_constraint(op.f('lma_templates_template_code_key'), 'lma_templates', type_='unique')
    op.create_index(op.f('ix_lma_templates_category'), 'lma_templates', ['category'], unique=False)
    op.create_index(op.f('ix_lma_templates_template_code'), 'lma_templates', ['template_code'], unique=True)
    op.create_index(op.f('ix_meetings_organizer_id'), 'meetings', ['organizer_id'], unique=False)
    op.add_column('notarization_records', sa.Column('securitization_pool_id', sa.Integer(), nullable=True))
    op.alter_column('notarization_records', 'deal_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_notarization_records_securitization_pool_id'), 'notarization_records', ['securitization_pool_id'], unique=False)
    op.create_foreign_key(None, 'notarization_records', 'securitization_pools', ['securitization_pool_id'], ['id'])
    op.add_column('payment_events', sa.Column('payer_wallet_address', sa.String(length=255), nullable=True))
    op.add_column('payment_events', sa.Column('receiver_wallet_address', sa.String(length=255), nullable=True))
    op.add_column('payment_events', sa.Column('payment_status', sa.String(length=50), nullable=False))
    op.add_column('payment_events', sa.Column('facilitator_url', sa.String(length=500), nullable=True))
    op.add_column('payment_events', sa.Column('payment_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('payment_events', sa.Column('related_deal_id', sa.Integer(), nullable=True))
    op.add_column('payment_events', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('payment_events', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('payment_events', 'payer_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Integer(),
               nullable=True,
               postgresql_using='payer_id::integer')
    op.alter_column('payment_events', 'receiver_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Integer(),
               nullable=True,
               postgresql_using='receiver_id::integer')
    op.alter_column('payment_events', 'related_trade_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using='related_trade_id::integer')
    op.alter_column('payment_events', 'related_loan_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using='related_loan_id::integer')
    op.drop_index(op.f('idx_payment_events_created_at'), table_name='payment_events')
    op.drop_index(op.f('idx_payment_events_payment_id'), table_name='payment_events')
    op.drop_index(op.f('idx_payment_events_related_loan_id'), table_name='payment_events')
    op.drop_index(op.f('idx_payment_events_related_trade_id'), table_name='payment_events')
    op.drop_index(op.f('idx_payment_events_status'), table_name='payment_events')
    op.drop_constraint(op.f('payment_events_payment_id_key'), 'payment_events', type_='unique')
    op.create_index(op.f('ix_payment_events_payer_id'), 'payment_events', ['payer_id'], unique=False)
    op.create_index(op.f('ix_payment_events_payer_wallet_address'), 'payment_events', ['payer_wallet_address'], unique=False)
    op.create_index(op.f('ix_payment_events_payment_id'), 'payment_events', ['payment_id'], unique=True)
    op.create_index(op.f('ix_payment_events_payment_status'), 'payment_events', ['payment_status'], unique=False)
    op.create_index(op.f('ix_payment_events_payment_type'), 'payment_events', ['payment_type'], unique=False)
    op.create_index(op.f('ix_payment_events_receiver_id'), 'payment_events', ['receiver_id'], unique=False)
    op.create_index(op.f('ix_payment_events_receiver_wallet_address'), 'payment_events', ['receiver_wallet_address'], unique=False)
    op.create_index(op.f('ix_payment_events_related_deal_id'), 'payment_events', ['related_deal_id'], unique=False)
    op.create_index(op.f('ix_payment_events_transaction_hash'), 'payment_events', ['transaction_hash'], unique=False)
    op.create_foreign_key(None, 'payment_events', 'users', ['receiver_id'], ['id'])
    op.create_foreign_key(None, 'payment_events', 'deals', ['related_deal_id'], ['id'])
    op.create_foreign_key(None, 'payment_events', 'users', ['payer_id'], ['id'])
    op.drop_column('payment_events', 'x402_settlement')
    op.drop_column('payment_events', 'related_facility_id')
    op.drop_column('payment_events', 'x402_payment_payload')
    op.drop_column('payment_events', 'status')
    op.drop_column('payment_events', 'payment_method')
    op.drop_column('payment_events', 'receiver_name')
    op.drop_column('payment_events', 'x402_verification')
    op.drop_column('payment_events', 'settled_at')
    op.drop_column('payment_events', 'payer_name')
    op.drop_constraint(op.f('permission_definitions_name_key'), 'permission_definitions', type_='unique')
    op.drop_index(op.f('idx_policy_decisions_created_at'), table_name='policy_decisions')
    op.drop_index(op.f('idx_policy_decisions_deal_id'), table_name='policy_decisions')
    op.drop_index(op.f('idx_policy_decisions_decision'), table_name='policy_decisions')
    op.drop_index(op.f('idx_policy_decisions_trace_id'), table_name='policy_decisions')
    op.drop_index(op.f('idx_policy_decisions_transaction'), table_name='policy_decisions')
    op.create_index(op.f('ix_policy_decisions_created_at'), 'policy_decisions', ['created_at'], unique=False)
    op.create_index(op.f('ix_policy_decisions_deal_id'), 'policy_decisions', ['deal_id'], unique=False)
    op.create_index(op.f('ix_policy_decisions_decision'), 'policy_decisions', ['decision'], unique=False)
    op.create_index(op.f('ix_policy_decisions_loan_asset_id'), 'policy_decisions', ['loan_asset_id'], unique=False)
    op.create_index(op.f('ix_policy_decisions_transaction_id'), 'policy_decisions', ['transaction_id'], unique=False)
    op.create_unique_constraint(None, 'policy_decisions', ['trace_id'])
    op.drop_constraint(op.f('fk_policy_decisions_loan_asset_id'), 'policy_decisions', type_='foreignkey')
    op.drop_constraint(op.f('policy_templates_name_key'), 'policy_templates', type_='unique')
    op.create_index(op.f('ix_policy_templates_name'), 'policy_templates', ['name'], unique=True)
    op.drop_constraint(op.f('policy_versions_created_by_fkey'), 'policy_versions', type_='foreignkey')
    op.drop_column('policy_versions', 'created_by')
    op.drop_column('policy_versions', 'changes_summary')
    op.drop_constraint(op.f('refresh_tokens_jti_key'), 'refresh_tokens', type_='unique')
    op.add_column('regulatory_filings', sa.Column('regulatory_body', sa.String(length=100), nullable=False))
    op.add_column('regulatory_filings', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('regulatory_filings', sa.Column('filed_at', sa.DateTime(), nullable=True))
    op.add_column('regulatory_filings', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index(op.f('idx_regulatory_filings_pool_id'), table_name='regulatory_filings')
    op.drop_index(op.f('idx_regulatory_filings_status'), table_name='regulatory_filings')
    op.create_index(op.f('ix_regulatory_filings_pool_id'), 'regulatory_filings', ['pool_id'], unique=False)
    op.create_index(op.f('ix_regulatory_filings_status'), 'regulatory_filings', ['status'], unique=False)
    op.drop_column('regulatory_filings', 'filing_body')
    op.drop_column('regulatory_filings', 'submitted_at')
    op.drop_column('regulatory_filings', 'filing_status')
    op.drop_constraint(op.f('remote_app_profiles_profile_name_key'), 'remote_app_profiles', type_='unique')
    op.drop_index(op.f('ix_remote_app_profiles_profile_name'), table_name='remote_app_profiles')
    op.create_index(op.f('ix_remote_app_profiles_profile_name'), 'remote_app_profiles', ['profile_name'], unique=True)
    op.drop_constraint(op.f('uq_role_permission'), 'role_permissions', type_='unique')
    op.add_column('securitization_pool_assets', sa.Column('asset_id', sa.String(length=255), nullable=False))
    op.add_column('securitization_pool_assets', sa.Column('asset_value', sa.Numeric(precision=20, scale=2), nullable=False))
    op.add_column('securitization_pool_assets', sa.Column('currency', sa.String(length=3), nullable=False))
    op.drop_index(op.f('idx_securitization_pool_assets_deal_id'), table_name='securitization_pool_assets')
    op.drop_index(op.f('idx_securitization_pool_assets_loan_asset_id'), table_name='securitization_pool_assets')
    op.drop_index(op.f('idx_securitization_pool_assets_pool_id'), table_name='securitization_pool_assets')
    op.drop_constraint(op.f('uq_securitization_pool_assets'), 'securitization_pool_assets', type_='unique')
    op.create_index(op.f('ix_securitization_pool_assets_deal_id'), 'securitization_pool_assets', ['deal_id'], unique=False)
    op.create_index(op.f('ix_securitization_pool_assets_loan_asset_id'), 'securitization_pool_assets', ['loan_asset_id'], unique=False)
    op.create_index(op.f('ix_securitization_pool_assets_pool_id'), 'securitization_pool_assets', ['pool_id'], unique=False)
    op.add_column('securitization_pools', sa.Column('cdm_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index(op.f('idx_securitization_pools_pool_id'), table_name='securitization_pools')
    op.drop_index(op.f('idx_securitization_pools_status'), table_name='securitization_pools')
    op.drop_constraint(op.f('securitization_pools_pool_id_key'), 'securitization_pools', type_='unique')
    op.create_index(op.f('ix_securitization_pools_pool_id'), 'securitization_pools', ['pool_id'], unique=True)
    op.create_index(op.f('ix_securitization_pools_status'), 'securitization_pools', ['status'], unique=False)
    op.add_column('securitization_tranches', sa.Column('tranche_id', sa.String(length=255), nullable=False))
    op.add_column('securitization_tranches', sa.Column('size', sa.Numeric(precision=20, scale=2), nullable=False))
    op.add_column('securitization_tranches', sa.Column('currency', sa.String(length=3), nullable=False))
    op.add_column('securitization_tranches', sa.Column('principal_remaining', sa.Numeric(precision=20, scale=2), nullable=False))
    op.add_column('securitization_tranches', sa.Column('interest_accrued', sa.Numeric(precision=20, scale=2), nullable=False))
    op.add_column('securitization_tranches', sa.Column('token_id', sa.String(length=255), nullable=True))
    op.add_column('securitization_tranches', sa.Column('owner_wallet_address', sa.String(length=255), nullable=True))
    op.add_column('securitization_tranches', sa.Column('cdm_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.drop_index(op.f('idx_securitization_tranches_pool_id'), table_name='securitization_tranches')
    op.create_index(op.f('ix_securitization_tranches_owner_wallet_address'), 'securitization_tranches', ['owner_wallet_address'], unique=False)
    op.create_index(op.f('ix_securitization_tranches_pool_id'), 'securitization_tranches', ['pool_id'], unique=False)
    op.create_index(op.f('ix_securitization_tranches_token_id'), 'securitization_tranches', ['token_id'], unique=True)
    op.create_index(op.f('ix_securitization_tranches_tranche_id'), 'securitization_tranches', ['tranche_id'], unique=False)
    op.drop_column('securitization_tranches', 'cdm_tranche_data')
    op.drop_column('securitization_tranches', 'tranche_size')
    op.drop_index(op.f('idx_template_field_mappings_template_field'), table_name='template_field_mappings')
    op.drop_index(op.f('idx_template_field_mappings_template_id'), table_name='template_field_mappings')
    op.create_index(op.f('ix_template_field_mappings_template_field'), 'template_field_mappings', ['template_field'], unique=False)
    op.create_index(op.f('ix_template_field_mappings_template_id'), 'template_field_mappings', ['template_id'], unique=False)
    op.drop_index(op.f('ix_users_permissions'), table_name='users', postgresql_using='gin')
    op.drop_index(op.f('ix_users_profile_data'), table_name='users', postgresql_using='gin')
    op.drop_constraint(op.f('fk_users_signup_reviewed_by'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'users', ['signup_reviewed_by'], ['id'])
    op.drop_constraint(op.f('verification_requests_verification_id_key'), 'verification_requests', type_='unique')
    op.drop_constraint(op.f('verification_requests_verification_link_token_key'), 'verification_requests', type_='unique')
    op.drop_index(op.f('ix_verification_requests_verification_id'), table_name='verification_requests')
    op.create_index(op.f('ix_verification_requests_verification_id'), 'verification_requests', ['verification_id'], unique=True)
    op.drop_index(op.f('ix_verification_requests_verification_link_token'), table_name='verification_requests')
    op.create_index(op.f('ix_verification_requests_verification_link_token'), 'verification_requests', ['verification_link_token'], unique=True)
    op.alter_column('workflows', 'priority',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'normal'::character varying"))
    op.drop_constraint(op.f('workflows_document_id_key'), 'workflows', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('workflows_document_id_key'), 'workflows', ['document_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('workflows', 'priority',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'normal'::character varying"))
    op.drop_index(op.f('ix_verification_requests_verification_link_token'), table_name='verification_requests')
    op.create_index(op.f('ix_verification_requests_verification_link_token'), 'verification_requests', ['verification_link_token'], unique=False)
    op.drop_index(op.f('ix_verification_requests_verification_id'), table_name='verification_requests')
    op.create_index(op.f('ix_verification_requests_verification_id'), 'verification_requests', ['verification_id'], unique=False)
    op.create_unique_constraint(op.f('verification_requests_verification_link_token_key'), 'verification_requests', ['verification_link_token'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('verification_requests_verification_id_key'), 'verification_requests', ['verification_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('fk_users_signup_reviewed_by'), 'users', 'users', ['signup_reviewed_by'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_users_profile_data'), 'users', ['profile_data'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_users_permissions'), 'users', ['permissions'], unique=False, postgresql_using='gin')
    op.drop_index(op.f('ix_template_field_mappings_template_id'), table_name='template_field_mappings')
    op.drop_index(op.f('ix_template_field_mappings_template_field'), table_name='template_field_mappings')
    op.create_index(op.f('idx_template_field_mappings_template_id'), 'template_field_mappings', ['template_id'], unique=False)
    op.create_index(op.f('idx_template_field_mappings_template_field'), 'template_field_mappings', ['template_field'], unique=False)
    op.add_column('securitization_tranches', sa.Column('tranche_size', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=False))
    op.add_column('securitization_tranches', sa.Column('cdm_tranche_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_securitization_tranches_tranche_id'), table_name='securitization_tranches')
    op.drop_index(op.f('ix_securitization_tranches_token_id'), table_name='securitization_tranches')
    op.drop_index(op.f('ix_securitization_tranches_pool_id'), table_name='securitization_tranches')
    op.drop_index(op.f('ix_securitization_tranches_owner_wallet_address'), table_name='securitization_tranches')
    op.create_index(op.f('idx_securitization_tranches_pool_id'), 'securitization_tranches', ['pool_id'], unique=False)
    op.drop_column('securitization_tranches', 'cdm_data')
    op.drop_column('securitization_tranches', 'owner_wallet_address')
    op.drop_column('securitization_tranches', 'token_id')
    op.drop_column('securitization_tranches', 'interest_accrued')
    op.drop_column('securitization_tranches', 'principal_remaining')
    op.drop_column('securitization_tranches', 'currency')
    op.drop_column('securitization_tranches', 'size')
    op.drop_column('securitization_tranches', 'tranche_id')
    op.drop_index(op.f('ix_securitization_pools_status'), table_name='securitization_pools')
    op.drop_index(op.f('ix_securitization_pools_pool_id'), table_name='securitization_pools')
    op.create_unique_constraint(op.f('securitization_pools_pool_id_key'), 'securitization_pools', ['pool_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_securitization_pools_status'), 'securitization_pools', ['status'], unique=False)
    op.create_index(op.f('idx_securitization_pools_pool_id'), 'securitization_pools', ['pool_id'], unique=True)
    op.drop_column('securitization_pools', 'cdm_data')
    op.drop_index(op.f('ix_securitization_pool_assets_pool_id'), table_name='securitization_pool_assets')
    op.drop_index(op.f('ix_securitization_pool_assets_loan_asset_id'), table_name='securitization_pool_assets')
    op.drop_index(op.f('ix_securitization_pool_assets_deal_id'), table_name='securitization_pool_assets')
    op.create_unique_constraint(op.f('uq_securitization_pool_assets'), 'securitization_pool_assets', ['pool_id', 'deal_id', 'loan_asset_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_securitization_pool_assets_pool_id'), 'securitization_pool_assets', ['pool_id'], unique=False)
    op.create_index(op.f('idx_securitization_pool_assets_loan_asset_id'), 'securitization_pool_assets', ['loan_asset_id'], unique=False)
    op.create_index(op.f('idx_securitization_pool_assets_deal_id'), 'securitization_pool_assets', ['deal_id'], unique=False)
    op.drop_column('securitization_pool_assets', 'currency')
    op.drop_column('securitization_pool_assets', 'asset_value')
    op.drop_column('securitization_pool_assets', 'asset_id')
    op.create_unique_constraint(op.f('uq_role_permission'), 'role_permissions', ['role', 'permission_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_remote_app_profiles_profile_name'), table_name='remote_app_profiles')
    op.create_index(op.f('ix_remote_app_profiles_profile_name'), 'remote_app_profiles', ['profile_name'], unique=False)
    op.create_unique_constraint(op.f('remote_app_profiles_profile_name_key'), 'remote_app_profiles', ['profile_name'], postgresql_nulls_not_distinct=False)
    op.add_column('regulatory_filings', sa.Column('filing_status', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('regulatory_filings', sa.Column('submitted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('regulatory_filings', sa.Column('filing_body', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_regulatory_filings_status'), table_name='regulatory_filings')
    op.drop_index(op.f('ix_regulatory_filings_pool_id'), table_name='regulatory_filings')
    op.create_index(op.f('idx_regulatory_filings_status'), 'regulatory_filings', ['filing_status'], unique=False)
    op.create_index(op.f('idx_regulatory_filings_pool_id'), 'regulatory_filings', ['pool_id'], unique=False)
    op.drop_column('regulatory_filings', 'metadata')
    op.drop_column('regulatory_filings', 'filed_at')
    op.drop_column('regulatory_filings', 'status')
    op.drop_column('regulatory_filings', 'regulatory_body')
    op.create_unique_constraint(op.f('refresh_tokens_jti_key'), 'refresh_tokens', ['jti'], postgresql_nulls_not_distinct=False)
    op.add_column('policy_versions', sa.Column('changes_summary', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('policy_versions', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('policy_versions_created_by_fkey'), 'policy_versions', 'users', ['created_by'], ['id'])
    op.drop_index(op.f('ix_policy_templates_name'), table_name='policy_templates')
    op.create_unique_constraint(op.f('policy_templates_name_key'), 'policy_templates', ['name'], postgresql_nulls_not_distinct=False)
    op.create_foreign_key(op.f('fk_policy_decisions_loan_asset_id'), 'policy_decisions', 'loan_assets', ['loan_asset_id'], ['id'])
    op.drop_constraint(None, 'policy_decisions', type_='unique')
    op.drop_index(op.f('ix_policy_decisions_transaction_id'), table_name='policy_decisions')
    op.drop_index(op.f('ix_policy_decisions_loan_asset_id'), table_name='policy_decisions')
    op.drop_index(op.f('ix_policy_decisions_decision'), table_name='policy_decisions')
    op.drop_index(op.f('ix_policy_decisions_deal_id'), table_name='policy_decisions')
    op.drop_index(op.f('ix_policy_decisions_created_at'), table_name='policy_decisions')
    op.create_index(op.f('idx_policy_decisions_transaction'), 'policy_decisions', ['transaction_id'], unique=False)
    op.create_index(op.f('idx_policy_decisions_trace_id'), 'policy_decisions', ['trace_id'], unique=True)
    op.create_index(op.f('idx_policy_decisions_decision'), 'policy_decisions', ['decision'], unique=False)
    op.create_index(op.f('idx_policy_decisions_deal_id'), 'policy_decisions', ['deal_id'], unique=False)
    op.create_index(op.f('idx_policy_decisions_created_at'), 'policy_decisions', ['created_at'], unique=False)
    op.create_unique_constraint(op.f('permission_definitions_name_key'), 'permission_definitions', ['name'], postgresql_nulls_not_distinct=False)
    op.add_column('payment_events', sa.Column('payer_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('payment_events', sa.Column('settled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('payment_events', sa.Column('x402_verification', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('payment_events', sa.Column('receiver_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('payment_events', sa.Column('payment_method', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('payment_events', sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('payment_events', sa.Column('x402_payment_payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('payment_events', sa.Column('related_facility_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('payment_events', sa.Column('x402_settlement', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'payment_events', type_='foreignkey')
    op.drop_constraint(None, 'payment_events', type_='foreignkey')
    op.drop_constraint(None, 'payment_events', type_='foreignkey')
    op.drop_index(op.f('ix_payment_events_transaction_hash'), table_name='payment_events')
    op.drop_index(op.f('ix_payment_events_related_deal_id'), table_name='payment_events')
    op.drop_index(op.f('ix_payment_events_receiver_wallet_address'), table_name='payment_events')
    op.drop_index(op.f('ix_payment_events_receiver_id'), table_name='payment_events')
    op.drop_index(op.f('ix_payment_events_payment_type'), table_name='payment_events')
    op.drop_index(op.f('ix_payment_events_payment_status'), table_name='payment_events')
    op.drop_index(op.f('ix_payment_events_payment_id'), table_name='payment_events')
    op.drop_index(op.f('ix_payment_events_payer_wallet_address'), table_name='payment_events')
    op.drop_index(op.f('ix_payment_events_payer_id'), table_name='payment_events')
    op.create_unique_constraint(op.f('payment_events_payment_id_key'), 'payment_events', ['payment_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_payment_events_status'), 'payment_events', ['status'], unique=False)
    op.create_index(op.f('idx_payment_events_related_trade_id'), 'payment_events', ['related_trade_id'], unique=False)
    op.create_index(op.f('idx_payment_events_related_loan_id'), 'payment_events', ['related_loan_id'], unique=False)
    op.create_index(op.f('idx_payment_events_payment_id'), 'payment_events', ['payment_id'], unique=True)
    op.create_index(op.f('idx_payment_events_created_at'), 'payment_events', ['created_at'], unique=False)
    op.alter_column('payment_events', 'related_loan_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('payment_events', 'related_trade_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('payment_events', 'receiver_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('payment_events', 'payer_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('payment_events', 'updated_at')
    op.drop_column('payment_events', 'metadata')
    op.drop_column('payment_events', 'related_deal_id')
    op.drop_column('payment_events', 'payment_payload')
    op.drop_column('payment_events', 'facilitator_url')
    op.drop_column('payment_events', 'payment_status')
    op.drop_column('payment_events', 'receiver_wallet_address')
    op.drop_column('payment_events', 'payer_wallet_address')
    op.drop_constraint(None, 'notarization_records', type_='foreignkey')
    op.drop_index(op.f('ix_notarization_records_securitization_pool_id'), table_name='notarization_records')
    op.alter_column('notarization_records', 'deal_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('notarization_records', 'securitization_pool_id')
    op.drop_index(op.f('ix_meetings_organizer_id'), table_name='meetings')
    op.drop_index(op.f('ix_lma_templates_template_code'), table_name='lma_templates')
    op.drop_index(op.f('ix_lma_templates_category'), table_name='lma_templates')
    op.create_unique_constraint(op.f('lma_templates_template_code_key'), 'lma_templates', ['template_code'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_lma_templates_template_code'), 'lma_templates', ['template_code'], unique=True)
    op.create_index(op.f('idx_lma_templates_subcategory'), 'lma_templates', ['subcategory'], unique=False)
    op.create_index(op.f('idx_lma_templates_category'), 'lma_templates', ['category'], unique=False)
    op.alter_column('lma_templates', 'file_path',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('lma_templates', 'version',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('lma_templates', 'template_code',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_index(op.f('ix_inquiries_resolved_by'), table_name='inquiries')
    op.drop_index(op.f('ix_inquiries_assigned_to'), table_name='inquiries')
    op.drop_index(op.f('ix_generated_documents_template_id'), table_name='generated_documents')
    op.drop_index(op.f('ix_generated_documents_status'), table_name='generated_documents')
    op.drop_index(op.f('ix_generated_documents_source_document_id'), table_name='generated_documents')
    op.drop_index(op.f('ix_generated_documents_created_by'), table_name='generated_documents')
    op.create_index(op.f('idx_generated_documents_template_id'), 'generated_documents', ['template_id'], unique=False)
    op.create_index(op.f('idx_generated_documents_status'), 'generated_documents', ['status'], unique=False)
    op.create_index(op.f('idx_generated_documents_source_document_id'), 'generated_documents', ['source_document_id'], unique=False)
    op.create_index(op.f('idx_generated_documents_created_by'), 'generated_documents', ['created_by'], unique=False)
    op.drop_column('generated_documents', 'source_type')
    op.drop_column('generated_documents', 'document_type')
    op.add_column('documents', sa.Column('is_demo', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_documents_template_id'), table_name='documents')
    op.create_index(op.f('ix_documents_is_demo'), 'documents', ['is_demo'], unique=False)
    op.create_index(op.f('idx_documents_template_id'), 'documents', ['template_id'], unique=False)
    op.alter_column('documents', 'sustainability_linked',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('document_versions', 'extraction_method',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'simple'::character varying"))
    op.add_column('document_signatures', sa.Column('requested_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('document_signatures', sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('document_signatures', sa.Column('signature_status', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('document_signatures', sa.Column('signed_document_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('document_signatures', sa.Column('signature_request_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('document_signatures', sa.Column('signers', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('document_signatures', sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('document_signatures', sa.Column('signed_document_path', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('document_signatures', sa.Column('signature_provider_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('document_signatures', sa.Column('signature_provider', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_document_signatures_signature_status'), 'document_signatures', ['signature_status'], unique=False)
    op.create_index(op.f('ix_document_signatures_signature_request_id'), 'document_signatures', ['signature_request_id'], unique=True)
    op.alter_column('document_signatures', 'document_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('document_signatures', 'created_at')
    op.drop_column('document_signatures', 'signed_at')
    op.drop_column('document_signatures', 'signature_data')
    op.drop_column('document_signatures', 'signature_method')
    op.drop_column('document_signatures', 'signer_role')
    op.drop_column('document_signatures', 'signer_name')
    op.alter_column('demo_seeding_status', 'errors',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_unique_constraint(op.f('deals_deal_id_key'), 'deals', ['deal_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('deals', 'is_demo',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_clause_cache_template_field_context'), 'clause_cache', ['template_id', 'field_name', 'context_hash'], unique=True)
    op.create_index(op.f('ix_applications_application_type'), 'applications', ['application_type'], unique=False)
    op.alter_column('applications', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'draft'::character varying"))
    op.alter_column('applications', 'application_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.create_table('payment_schedules',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('loan_asset_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('payment_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('scheduled_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('payment_frequency_period', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('payment_frequency_multiplier', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('processed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('payment_schedules_pkey'))
    )
    op.create_index(op.f('ix_payment_schedules_status'), 'payment_schedules', ['status'], unique=False)
    op.create_index(op.f('ix_payment_schedules_scheduled_date'), 'payment_schedules', ['scheduled_date'], unique=False)
    op.create_index(op.f('ix_payment_schedules_loan_asset_id'), 'payment_schedules', ['loan_asset_id'], unique=False)
    # ### end Alembic commands ###
