"""add_permission_keys_and_sharing_events

Revision ID: c80aa4258269
Revises: cd9212310e52
Create Date: 2026-01-17 16:35:52.378072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy import Text

# revision identifiers, used by Alembic.
revision: str = 'c80aa4258269'
down_revision: Union[str, Sequence[str], None] = 'cd9212310e52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key_id', sa.String(length=255), nullable=False),
    sa.Column('key_type', sa.String(length=50), nullable=False),
    sa.Column('encrypted_key', JSONB(astext_type=sa.Text()), nullable=False),  # EncryptedJSON stored as JSONB
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('workflow_id', sa.String(length=255), nullable=True),
    sa.Column('wallet_address', sa.String(length=255), nullable=True),
    sa.Column('application_key_id', sa.String(length=255), nullable=True),
    sa.Column('whitelist_id', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('download_ttl', sa.DateTime(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permission_keys_application_key_id'), 'permission_keys', ['application_key_id'], unique=False)
    op.create_index(op.f('ix_permission_keys_deal_id'), 'permission_keys', ['deal_id'], unique=False)
    op.create_index(op.f('ix_permission_keys_document_id'), 'permission_keys', ['document_id'], unique=False)
    op.create_index(op.f('ix_permission_keys_download_ttl'), 'permission_keys', ['download_ttl'], unique=False)
    op.create_index(op.f('ix_permission_keys_expires_at'), 'permission_keys', ['expires_at'], unique=False)
    op.create_index(op.f('ix_permission_keys_key_hash'), 'permission_keys', ['key_hash'], unique=False)
    op.create_index(op.f('ix_permission_keys_key_id'), 'permission_keys', ['key_id'], unique=True)
    op.create_index(op.f('ix_permission_keys_key_type'), 'permission_keys', ['key_type'], unique=False)
    op.create_index(op.f('ix_permission_keys_organization_id'), 'permission_keys', ['organization_id'], unique=False)
    op.create_index(op.f('ix_permission_keys_wallet_address'), 'permission_keys', ['wallet_address'], unique=False)
    op.create_index(op.f('ix_permission_keys_whitelist_id'), 'permission_keys', ['whitelist_id'], unique=False)
    op.create_index(op.f('ix_permission_keys_workflow_id'), 'permission_keys', ['workflow_id'], unique=False)
    op.create_table('sharing_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('sharing_method', sa.String(length=50), nullable=False),
    sa.Column('workflow_id', sa.String(length=255), nullable=True),
    sa.Column('deal_id', sa.Integer(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('sender_user_id', sa.Integer(), nullable=False),
    sa.Column('receiver_user_id', sa.Integer(), nullable=True),
    sa.Column('receiver_email', sa.String(length=255), nullable=True),
    sa.Column('receiver_wallet_address', sa.String(length=255), nullable=True),
    sa.Column('file_hash', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('files_included', sa.Integer(), nullable=False),
    sa.Column('blockchain_tx_hash', sa.String(length=255), nullable=True),
    sa.Column('blockchain_block_number', sa.Integer(), nullable=True),
    sa.Column('notarized_at', sa.DateTime(), nullable=True),
    sa.Column('cdm_event', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receiver_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sharing_events_blockchain_tx_hash'), 'sharing_events', ['blockchain_tx_hash'], unique=False)
    op.create_index(op.f('ix_sharing_events_created_at'), 'sharing_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_sharing_events_deal_id'), 'sharing_events', ['deal_id'], unique=False)
    op.create_index(op.f('ix_sharing_events_document_id'), 'sharing_events', ['document_id'], unique=False)
    op.create_index(op.f('ix_sharing_events_event_id'), 'sharing_events', ['event_id'], unique=True)
    op.create_index(op.f('ix_sharing_events_event_type'), 'sharing_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_sharing_events_file_hash'), 'sharing_events', ['file_hash'], unique=False)
    op.create_index(op.f('ix_sharing_events_receiver_email'), 'sharing_events', ['receiver_email'], unique=False)
    op.create_index(op.f('ix_sharing_events_receiver_user_id'), 'sharing_events', ['receiver_user_id'], unique=False)
    op.create_index(op.f('ix_sharing_events_receiver_wallet_address'), 'sharing_events', ['receiver_wallet_address'], unique=False)
    op.create_index(op.f('ix_sharing_events_sender_user_id'), 'sharing_events', ['sender_user_id'], unique=False)
    op.create_index(op.f('ix_sharing_events_workflow_id'), 'sharing_events', ['workflow_id'], unique=False)
    # Note: EncryptedString columns are stored as TEXT/VARCHAR in database
    # The encryption is handled at the application level
    op.alter_column('loan_assets', 'collateral_address',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('payment_events', 'payer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('payment_events', 'receiver_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('staged_extractions', 'source_filename',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('staged_extractions', 'source_filename',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('payment_events', 'receiver_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('payment_events', 'payer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('loan_assets', 'collateral_address',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.drop_index(op.f('ix_sharing_events_workflow_id'), table_name='sharing_events')
    op.drop_index(op.f('ix_sharing_events_sender_user_id'), table_name='sharing_events')
    op.drop_index(op.f('ix_sharing_events_receiver_wallet_address'), table_name='sharing_events')
    op.drop_index(op.f('ix_sharing_events_receiver_user_id'), table_name='sharing_events')
    op.drop_index(op.f('ix_sharing_events_receiver_email'), table_name='sharing_events')
    op.drop_index(op.f('ix_sharing_events_file_hash'), table_name='sharing_events')
    op.drop_index(op.f('ix_sharing_events_event_type'), table_name='sharing_events')
    op.drop_index(op.f('ix_sharing_events_event_id'), table_name='sharing_events')
    op.drop_index(op.f('ix_sharing_events_document_id'), table_name='sharing_events')
    op.drop_index(op.f('ix_sharing_events_deal_id'), table_name='sharing_events')
    op.drop_index(op.f('ix_sharing_events_created_at'), table_name='sharing_events')
    op.drop_index(op.f('ix_sharing_events_blockchain_tx_hash'), table_name='sharing_events')
    op.drop_table('sharing_events')
    op.drop_index(op.f('ix_permission_keys_workflow_id'), table_name='permission_keys')
    op.drop_index(op.f('ix_permission_keys_whitelist_id'), table_name='permission_keys')
    op.drop_index(op.f('ix_permission_keys_wallet_address'), table_name='permission_keys')
    op.drop_index(op.f('ix_permission_keys_organization_id'), table_name='permission_keys')
    op.drop_index(op.f('ix_permission_keys_key_type'), table_name='permission_keys')
    op.drop_index(op.f('ix_permission_keys_key_id'), table_name='permission_keys')
    op.drop_index(op.f('ix_permission_keys_key_hash'), table_name='permission_keys')
    op.drop_index(op.f('ix_permission_keys_expires_at'), table_name='permission_keys')
    op.drop_index(op.f('ix_permission_keys_download_ttl'), table_name='permission_keys')
    op.drop_index(op.f('ix_permission_keys_document_id'), table_name='permission_keys')
    op.drop_index(op.f('ix_permission_keys_deal_id'), table_name='permission_keys')
    op.drop_index(op.f('ix_permission_keys_application_key_id'), table_name='permission_keys')
    op.drop_table('permission_keys')
    # ### end Alembic commands ###
